### PR TITLE
excel-export/ui: Fix translations

### LINKED ISSUE #655: 1.16.0 French translations
Issue Type | Description of issue | English term | Current french translation | French translation needed
-- | -- | -- | -- | --
Translation / Terminology | Data not translated in the exported file | Project ID | Project ID | ID du Projet
Translation / Terminology | Data not translated in the exported file | Project Name | Projet Nom | Nom du Projet
Translation / Terminology | Data not translated in the exported file : in the status column | Open | Open | Ouvert
Translation / Terminology | Data not translated in the exported file : in the status column | Closed | Closed | Validé
Translation / Terminology | Data not translated in the exported file | Created | Créé | Date de création
Translation / Terminology | Workflow Item Type in export file | Restricted | Restricted | Restreint
Translation / Terminology | Document sheet in the exported file | Name (should be document name ?) | Nom | Nom du document
Translation / Terminology | Main page, in the description of every project | Created | Créé | Date de création

### PR DESCRIPTION
**Pull request by georgimld**
### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/master/CONTRIBUTING.md).

### Description

This PR:
    - fixes some ui and excel export translations
    - maps results from the api in the export service to the correct translations for the excel export
    - adds a dev script to package.json

Closes #655

### CODE REVIEW

File: excel-export/src/helper.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    case "N/A":
+      return strings.workflowitem.na;
+    case "allocated":
+      return strings.workflowitem.allocated;
+    case "disbursed":
+      return strings.workflowitem.disbursed;
+    default:
+      break;
+  }
+};
```
Comment (daniel-arnauer) [inline excel-export/src/helper.ts:36]: Proof if the right translations are used after changing the language. A problem occured in the frontend, when the string is allocated outside a React component which leads to a wrong translations
see: https://github.com/openkfw/TruBudget/pull/652

**Review by daniel-arnauer — APPROVED** [review]
approved
