### PR TITLE
api:additional check for token inside error

### LINKED ISSUE #1367: API: Missing token crashes the server
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

Accessing `userId` if `token` is undefined crashes the api server.

 const message = `User ${err.token.userId} is not authorized.`;

### PR DESCRIPTION
**Pull request by egdmrsy**
### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [ ] I fixed all necessary PR warnings
- [x] The commit history is clean
- [x] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [x] I did a self review before requesting a review from another team member

### Description

Closes #1367 

Added additional check for the token inside error. If it is undefined, userId is not printed in the log.

### CODE REVIEW

File: api/src/httpd/router.ts [hunk 1]
```diff
@@ -28,7 +28,11 @@ const send = (res, httpResponse: HttpResponse): void => {
 const handleError = (_req, res, err): void => {
   switch (err.kind) {
     case "NotAuthorized": {
-      const message = `User ${err.token.userId} is not authorized.`;
+      let message = "Current user is not authorized.";
+      if (err.token) {
+        message = "User ${err.token.userId} is not authorized.";
```
Comment (SamuelPull) [inline api/src/httpd/router.ts:33]: Without template string, this just prints `User ${err.token.userId} is not authorized.`  
I suggest
``` 
message = `User ${err.token?.userId} is not authorized.`;
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -28,6 +28,7 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 
 ### Fixed
 
+- Fixed a bug where missing token would crash the api. [#1367](https://github.com/openkfw/TruBudget/issues/1367)
```
Comment (georgimld) [inline CHANGELOG.md:31]: no need for changelog entry, as the bug is not relevant for Trubudget users or operators

**Review by georgimld — APPROVED** [review]
