### PR TITLE
Exclude rejected WFI from assigned budget

### LINKED ISSUE #1275: Amount of rejected WFI on dashboard
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
Amounts rejected on SIGFE are counted in the dashboard. (Both in Project details and Subproject Details)
Note: This is a frontend issue, as assigned budget is only calculated on the frontend. Api does not keep track of custom calculated budget for data visualisation purposes.
### How to reproduce 🕹
**Scenario 1**
1- Create a workflow item under any subproject with an allocated budget amount. (Assigned)
2- Reject the workflow item (Reject reason is not important)
3- Click on Details button above to open Subproject details. (Under Projected Budget section)
4- The allocated amount of the rejected WFI is still added to the assigned amount.
5- Go back to Project page and click on the Details button above to open Project details. (Under Total Budget section)
6- Same result as Step 4.
**Scenario 2**
1- Repeat step 1 from Scenario 1 but instead of "assigned" wfi, create a "paid" wfi.
2- Reject the paid wfi.
3- Repeat the remaining steps from Scenario 1, the focus is "paid amount" instead of the "assigned amount"

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v1.?.?  |
| API             | v1.?.?  |
| Blockchain      | v1.?.?  |
| Export-Service  | v1.?.?  |
| Email-Service   | v1.?.?  |
| Storage-Service | v1.?.?  |

### PR DESCRIPTION
**Pull request by egdmrsy**
### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [x] I fixed all necessary PR warnings
- [x] The commit history is clean
- [x] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [x] I did a self review before requesting a review from another team member

### Description

Added a check for rejected workflow items before calculating the assigned budget for project and subproject detail views.

Closes #1275

### CODE REVIEW

File: frontend/src/sagas.js [hunk 1]
```diff
@@ -2798,8 +2798,8 @@ export function* getProjectKPIsSaga({ projectId, showLoading = true }) {
               error.name = "redacted";
               throw error;
             }
-            const { amountType, status, amount, exchangeRate } = next.data;
-            if (amountType === "allocated" && status === "closed" && amount) {
+            const { amountType, status, amount, exchangeRate, rejectReason } = next.data;
+            if (amountType === "allocated" && status === "closed" && amount && !rejectReason) {
               return {
                 ...acc,
                 allocated: acc.allocated + fromAmountString(amount) * (exchangeRate || 1)
```
Comment (georgimld) [inline frontend/src/sagas.js:2805]: the same should probably be implemented for payed (disbursed) budget too, no?

**Review by georgimld — CHANGES_REQUESTED** [review]
- [ ] add e2e-tests here https://github.com/openkfw/TruBudget/blob/main/e2e-test/cypress/integration/subproject_analytics_spec.js
- [ ] add changelog entry for fixing the bug
