### PR TITLE
multichain-feed and email-service improvement

### LINKED ISSUE #1817: multichain-feed not working (?)
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

### How to reproduce 🕹

1. <E.g. login as user XYZ>
2. <E.g. try to create new subproject>
3. <E.g. You will see error in console>
4. ...

### Screenshots 📷

Add screenshots or screen recording video if applicable.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.?.?  |
| API             | v2.?.?  |
| Blockchain      | v2.?.?  |
| Export-Service  | v2.?.?  |
| Email-Service   | v2.?.?  |
| Storage-Service | v2.?.?  |

### PR DESCRIPTION
**Pull request by SamuelPull**
### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [x] I fixed all necessary PR warnings
- [x] The commit history is clean
- [x] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [x] I did a self review before requesting a review from another team member

### How to test

1. <E.g. login as user XYZ>
2. <E.g. try to create new subproject>
3. <E.g. You should not see error in console>
4. ...

Closes #1817

### CODE REVIEW

File: email-notification-service/src/index.ts [hunk 1]
```diff
@@ -286,25 +292,27 @@ emailService.post(
...
+            notification: { recipient: id, status: "sent", emailAddress },
+          };
+          res.status(200).send(body);
+        } else {
+          logger.trace("Email address" + emailAddress + "not found");
+          body = { notification: { recipient: id, status: "deleted", emailAddress: "Not Found" } };
+          res.status(404).send(body);
+        }
+      } catch (error) {
+        logger.error({ err: error }, "Error while send notification");
```
Comment (galethil) [inline email-notification-service/src/index.ts:312]: @SamuelPull in my experience, when using logger, the second (third, fourth, etc.) parameter is ignored on final terminal output.

**Review by galethil — APPROVED** [review]
