### PR TITLE
ui: update workflow edit invalid date

### LINKED ISSUE #708: frontend: Workflowitem with no due date shows invalid date in new datepicker
An empty date is shown as an invalid date in the new date picker

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Screenshot 2020-12-14 at 16 36 38

## Expected Behavior 🤔

No date should show empty line, not error.

## Steps to Reproduce 🕹

Steps:

1. Create a workflowitem with no due date
2. Edit that workflowitem
3. Bim 💣
4. ☠️

## Your Environment 🌎

| Tech           | Version |
| -------------- | ------- |
| Frontend       | v1.?.?  |
| API            | v1.?.?  |
| Blockchain     | v1.?.?  |
| Export-Service | v1.?.?  |
| Email-Service  | v1.?.?  |
| Chrome-Browser | ?       |
| etc.           |         |

### PR DESCRIPTION
**Pull request by pheolink**
Closes #708

### CODE REVIEW

File: frontend/src/pages/Common/DatePicker.js [hunk 1]
```diff
@@ -26,6 +26,7 @@ const styles = {
 function DatePicker({ classes, name, label, onChange, onDelete, datetime, id = "default" }) {
   const dateFormat = strings.format.dateFormat;
   const datePlaceholder = strings.format.datePlaceholder;
+  const dateValue = datetime ? datetime : null;
   return (
```
Comment (daniel-arnauer) [inline frontend/src/pages/Common/DatePicker.js:30]: a better solution in my opinion, because if the string is empty, your version will not work. 
This will set dateValue to null if dateTime is `"", undefined, null, {}, []`:

`const dateValue = _isEmpty(datetime) ? datetime : null;`

Comment (daniel-arnauer) [reply frontend/src/pages/Common/DatePicker.js:30]: `import _isEmpty from "lodash/isEmpty";`

File: e2e-test/cypress/integration/workflowitem_edit_spec.js [hunk 2]
```diff
@@ -64,6 +64,22 @@ describe("Workflowitem edit", function() {
...
+    // Create a workflowitem
+    cy.createWorkflowitem(projectId, subprojectId, "workflowitem edit test", {
+      dueDate: ""
+    }).then(({ id }) => {
+      workflowitemId = id;
+      cy.visit(`/projects/${projectId}/${subprojectId}`);
+      // Edit workflow item
+      cy.get("[data-test=workflowitem-" + workflowitemId + "]").should("be.visible");
+      cy.get("[data-test=workflowitem-" + workflowitemId + "] [data-test=edit-workflowitem]").click();
+    });
```
Comment (daniel-arnauer) [inline e2e-test/cypress/integration/workflowitem_edit_spec.js:80]: You do not check if the value is empty.
You do not check if no error is shown.

**Review by daniel-arnauer — APPROVED** [review]
approved
