### PR TITLE
Validate assignee when creating workflow item

### LINKED ISSUE #1327: Workflow items with non-existing assignee cannot be modified
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

During creating a workflow item directly through the API, when the value for the assignee is a user that does not exist in the system, workflow item is still created on-chain. However the workflow item cannot be modified at all because the "user not found" error is thrown.

### How to reproduce 🕹
1- Create a workflow item through API with assignee as a username that does not exist in the system. (e.g "exampleuser")
2- As a user with full permissions on the workflow item, try to modify the workflow item. (e.g changing exchange rate or bringing it to "paid" status)
3- Clicking on submit produces an error stating that the assigned user is not found and the request fails.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.1.0  |
| API             | v2.1.0  |
| Blockchain      | v2.1.0  |

### PR DESCRIPTION
**Pull request by egdmrsy**
### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [x] I fixed all necessary PR warnings
- [x] The commit history is clean
- [x] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [x] I did a self review before requesting a review from another team member

### Description

2 validations on API Level are added:
1- Disabled users are not allowed to be assigned to workflow items.
2- Users that do not exist are not allowed to be assigned to workflow items.

Closes #1327

### CODE REVIEW

File: api/src/service/domain/workflow/workflowitem_create.ts [hunk 1]
```diff
@@ -201,6 +204,17 @@ export async function createWorkflowitem(
     return new AlreadyExists(ctx, workflowitemCreated, workflowitemCreated.workflowitem.id);
   }
 
+  logger.trace({ item: workflowitemCreated }, "Check if assignee exists");
+  const isUserExists = await repository.userExists(
```
Comment (georgimld) [inline api/src/service/domain/workflow/workflowitem_create.ts:208]: in the TB api, we wrap return values in a `Result.Type`, which can also be an error - in this case you can check the [implementation of `userExists`](https://github.com/openkfw/TruBudget/blob/a0c42c2b74c532242eb3e87bda2e8324f622ecad/api/src/service/domain/organization/user_query.ts#L49) to see which errors it can return and in which cases.

Because of this, you must first check that the returned value is not an error and then use it the way you did. here is an example how this should be done: https://github.com/openkfw/TruBudget/blob/a0c42c2b74c532242eb3e87bda2e8324f622ecad/api/src/service/domain/organization/user_create.ts#L84

File: api/src/service/domain/workflow/workflowitem_create.ts [hunk 2]
```diff
@@ -201,6 +204,17 @@ export async function createWorkflowitem(
...
+    workflowitemCreated.workflowitem.assignee
+  );
+
+  if(!isUserExists) {
```
Comment (georgimld) [inline api/src/service/domain/workflow/workflowitem_create.ts:212]: I would also not name the const `isUserExists` - this sounds gramatically incorrect - just `userExists` is fine

File: api/src/service/domain/workflow/workflowitem_create.spec.ts [hunk 3]
```diff
@@ -41,6 +41,7 @@ describe("Create workflowitem", () => {
 
     const result = await WorkflowitemCreate.createWorkflowitem(ctx, root, data, {
       workflowitemExists: async (_projectId, _subprojectId, _workflowitemId) => false,
+      userExists: async (_userId) => true,
```
Comment (georgimld) [inline api/src/service/domain/workflow/workflowitem_create.spec.ts:44]: Please also add a new testcase that tests what you added, so if the user does not exist.

Also: what happens if you try this with a user that exists but is disabled? does this (and should this) still work?

File: api/src/service/domain/workflow/workflowitem_create.ts [hunk 4]
```diff
@@ -201,6 +207,42 @@ export async function createWorkflowitem(
...
+    workflowitemCreated.workflowitem.assignee
+    );
+
+  if (Result.isErr(userResult)) {
+    return new VError(userResult, "user check failed");
+  }
+
+  const userPermissions = userResult.permissions;
+
+  if(userPermissions["user.authenticate"] === undefined || userPermissions["user.authenticate"].length === 0) {
```
Comment (georgimld) [inline api/src/service/domain/workflow/workflowitem_create.ts:238]: the way you did it is fine but here's a short tipp how you can write cleaner code, you could refactor it this way:

`if(!userPermissions["user.authenticate"] || !userPermissions["user.authenticate"].length)`

File: api/src/service/domain/workflow/workflowitem_create.ts [hunk 5]
```diff
@@ -201,6 +207,42 @@ export async function createWorkflowitem(
...
+    return new VError(userResult, "user check failed");
+  }
+
+  const userPermissions = userResult.permissions;
+
+  if(!userPermissions["user.authenticate"] || !userPermissions["user.authenticate"].length) {
+    return new PreconditionError(
+      ctx,
+      workflowitemCreated,
+      "disabled users are not allowed to create workflow items!"
```
Comment (georgimld) [inline api/src/service/domain/workflow/workflowitem_create.ts:242]: the message should be `disabled users are not allowed to be assigned to workflowitems`

**Review by georgimld — APPROVED** [review]
