### PR TITLE
Docker-Compose Refactoring

### LINKED ISSUE #904: docker-compose developer setup
## Description 💡

Follow up issue for #896 

- [x] Per default, services should run with hot reload.
- [x] Per default set option for provisioning -> --noprovisioning

### LINKED ISSUE #905: Create Trubudget start script for operation teams
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Trubudget has already a [start script](https://github.com/openkfw/TruBudget/blob/master/scripts/development/start-dev.sh). This start script is created for developers and not flexible enough for operation teams.
This issue is about creating a new start script for operation teams similar to the developer start script including more options like a provision option or enable service options.

## TODOs

- [x] Add new Trubudget start script including more options for operation teams
- [x] default behaviour of the script should be the setup of Trubudget core components excluding provisioning and without any debug option enabled
- [ ] separate docker-compose files of Trubudget's core components and its optional services like provisioning or email service 
- [ ] check all docker-compose files and scripts. Delete them if the script can handle the setup instead (also think about a new option if its not yet possible to do it via script)
- [ ] check documentation update deprecated links and reference the new script in the operations/installation guide

### Script options for operation teams
-  `--provision` - start provisioning service and generate test data for the setup
- `--enable-service [service-name]` - enable the service specified (include the docker-compose.yml of the specific service)

### LINKED ISSUE #911: bump-tag-version script does not update the version
- [x ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
When running the `bump-tag-version` the script does not update the version. It only executes `npm install` in each sub-project.

### How to reproduce 🕹
Execute `bump-tag-version.sh v1.25`  in every `package.json` the version should be 1.25.

### PR DESCRIPTION
**Pull request by daniel-arnauer**
Developer setup:
- [x] Per default, services should run with hot reload.
- [x] Per default set option for provisioning -> --no-provision

Operation setup:
- [x] Add new Trubudget start script including more options for operation teams
- [x] default behaviour of the script should be the setup of Trubudget core components excluding provisioning and without any debug option enabled
- [ ] ~~separate docker-compose files of Trubudget's core components and its optional services like provisioning or email service~~
- [x] check all docker-compose files and scripts. Delete them if the script can handle the setup instead (also think about a new option if its not yet possible to do it via script)
- [x] check documentation update deprecated links and reference the new script in the operations/installation guide
- [x]  `--provision` - start provisioning service and generate test data for the setup
- [x] `--enable-service [service-name]` - enable the service specified (include the docker-compose.yml of the specific service)

Closes #904 
Closes #905
Closes #911 

Follow up: #932

### CODE REVIEW

File: scripts/k8lr [hunk 1]
```diff
@@ -1,21 +0,0 @@
-#!/bin/sh
```
Comment (mayrmartin) [inline scripts/k8lr:1]: Shouldn't we keep this file for k8s deployments?

File: scripts/operation/start-trubudget.sh [hunk 2]
```diff
@@ -0,0 +1,214 @@
...
+    sed -i 's/MULTICHAIN_FEED=.*/MULTICHAIN_FEED=DISABLED/g' ${SCRIPT_DIR}/.env
+    sed -i 's/REACT_APP_EMAIL_SERVICE_ENABLED=.*/REACT_APP_EMAIL_SERVICE_ENABLED=false/g' ${SCRIPT_DIR}/.env
+    sed -i 's/REACT_APP_EXPORT_SERVICE_ENABLED=.*/REACT_APP_EXPORT_SERVICE_ENABLED=false/g' ${SCRIPT_DIR}/.env
+    sed -i 's/DOCUMENT_FEATURE_ENABLED=.*/DOCUMENT_FEATURE_ENABLED=false/g' ${SCRIPT_DIR}/.env
+fi
+
+if [ "$HAS_ENABLED_SERVICES" = true ]; then
+    # Add services to slim version
+    selectedServices=`echo $ENABLED_SERVICES | awk -F ' ' '{ s = $1; for (i = 2; i <= NF; i++) s = s "\n"$i; print s; }'`
+    # sed command syntax:  sed -i 's/regexToReplace/SomethingToPutInInstead/g' /Some/Path/To/File.txt
```
Comment (mayrmartin) [inline scripts/operation/start-trubudget.sh:137]: remove unnecessary comment

File: scripts/operation/start-trubudget.sh [hunk 3]
```diff
@@ -0,0 +1,214 @@
...
+    for word in ${selectedServices}
+    do
+        # echo "This is the word $word"
```
Comment (mayrmartin) [inline scripts/operation/start-trubudget.sh:140]: remove

File: scripts/operation/start-trubudget.sh [hunk 4]
```diff
@@ -0,0 +1,214 @@
...
+    fi
+fi
+
+COMPOSE="docker-compose -f $SCRIPT_DIR/docker-compose.yml -p trubudget-operation --env-file $SCRIPT_DIR/.env"
+$COMPOSE down
+
+echo "INFO: Pull images from https://hub.docker.com/ ..."
+$COMPOSE pull
+
+#ToDo: Only use Images from Dockerhub
```
Comment (mayrmartin) [inline scripts/operation/start-trubudget.sh:204]: is todo done?

File: docker-compose/README.md [hunk 5]
```diff
@@ -1,6 +1,7 @@
 `docker-compose` files for running TruBudget:
 
-- [`local`](./local/): builds images from source
+<!-- - [`local`](./local/): builds images from source
```
Comment (mayrmartin) [inline docker-compose/README.md:3]: remove comment

File: docs/developer/developer-setup.md [hunk 6]
```diff
@@ -161,23 +161,19 @@ All projects in TruBudget (blockchain, api, frontend, etc) have a docker-compose
 Do **NOT** use other additional ways to set environment variables like inline env-variables or env-variables defined by 'export'. Why? - Because these env-variables will overwrite each which makes it very hard to find mistakes.
```
Comment (mayrmartin) [inline docs/developer/developer-setup.md:161]: Consider using danger/alert instead of note. 
Insert a extra line break before admonitions

File: docs/developer/developer-setup.md [hunk 7]
```diff
@@ -161,23 +161,19 @@ All projects in TruBudget (blockchain, api, frontend, etc) have a docker-compose
...
 If you want to start developing on Trubudget, you need to setup the application locally. This guide tells you how to start the blockchain, start the API, load up some test data and start the frontend.
 
-### Dockerized Application
+### Dockerized Application (recommended)
 
-This is the fastes way you can run all services needed for development. Everything is run in one command:
+This is the fastest way you can run **all services** needed for development. Everything is started in one command:
 
-1.  in root directory execute: `sh scripts/development/start-dev.sh --full` or `sh scripts/development/start-dev.sh --slim`
+1.  in root directory execute: `bash scripts/development/start-dev.sh --slim` or `bash scripts/development/start-dev.sh --full`
```
Comment (mayrmartin) [inline docs/developer/developer-setup.md:172]: Where is step 2?

File: docs/developer/developer-setup.md [hunk 8]
```diff
@@ -190,15 +186,15 @@ Following services are dockerized:
...
 
 The frontend should be availaible as usual at http://localhost:3000
 
 Docker Compose ensures that services are communicating and have correct environment variables set. Docker Compose puts all services in the same network and exposes needed ports.
 
-You can inspect each container individually: `docker logs --follow CONTAINER`. Where _CONTAINER_ represents selected value of NAMES column container in output of `docker ps` command.
+You can inspect each container individually: `docker logs --follow CONTAINER`. Where _CONTAINER_ represents name of the service that can be found in the `.yml` file.
 
 :::note
 Hot reloading with docker requires a lot of processing power (due to docker volumes). If you experience huge delays while hot-reloading, you should start the services you need by yourself without docker.
```
Comment (mayrmartin) [inline docs/developer/developer-setup.md:200]: Dockerized Application (recommended) guide ends here. Make clear, that the following **is not** needed if using docker.

File: docs/developer/introduction.md [hunk 9]
```diff
@@ -115,7 +115,7 @@ describe. For example, take a look at [api/src/](https://github.com/openkfw/TruB
 [githubdiscussions]: https://github.com/openkfw/TruBudget/discussions
 [architecture decision records (adr)]: http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions
 [doc/architecture/decisions]: ./architecture/intro.md
-[developer setup]: https://github.com/openkfw/TruBudget/blob/master/doc/installation/Developer-Setup.md#developer-setup/
+[developer setup]: https://github.com/openkfw/TruBudget/blob/master/docs/developer/developer-setup.md#developer-setup/
```
Comment (mayrmartin) [inline docs/developer/introduction.md:118]: **DO NOT** use absolut path to GitHub. Use relativ link. This will break the documentation!

File: e2e-test/README.md [hunk 10]
```diff
@@ -2,7 +2,7 @@
 
 This folder contains end-to-end tests which test the whole functionality of the application.
 
-For the setup of the e2e-tests please visit the [Developer-Setup](https://github.com/openkfw/TruBudget/blob/master/doc/installation/Developer-Setup.md#tests)
+For the setup of the e2e-tests please visit the [Developer Setup](https://github.com/openkfw/TruBudget/blob/master/docs/developer/developer-setup.md#tests)
```
Comment (mayrmartin) [inline e2e-test/README.md:5]: **DO NOT** use absolut path to GitHub. Use relativ link. This will break the documentation!

**Review by mayrmartin — CHANGES_REQUESTED** [review]

**Comment by daniel-arnauer** [comment]
To do:
Edit dev.md, connect-docker-compose.md, create-new-docker-compose.md, update-trubudget.md.
Add README.md for developer and operation bash script

File: README.md [hunk 11]
```diff
@@ -10,12 +10,21 @@ To fully understand the idea and motivation behind Trubudget, watch following vi
...
-## Installation
+## Getting started
+
+If you want to try out TruBudget locally, you need to install [Docker](https://www.docker.com/community-edition#/download).
+
+To setup TruBudget, run:
 
-Trubudget can be installed in different ways. Choose your prefered installation guide:
+```bash
+sh scripts/development/start-dev.sh --slim
```
[the remark this answers is not in the document]
Comment (daniel-arnauer) [reply README.md:20]: done

File: .gitignore [hunk 12]
```diff
@@ -11,3 +11,4 @@ yarn-error.log
 *.code-workspace
 .vs/
 e2e-test/debug.log
+scripts/development/.env
```
[the remark this answers is not in the document]
Comment (daniel-arnauer) [reply .gitignore:14]: done

File: scripts/k8lr (hunk 1 above)
Comment (daniel-arnauer) [reply scripts/k8lr:1]: can be removed

File: scripts/operation/start-trubudget.sh (hunk 2 above)
Comment (daniel-arnauer) [reply scripts/operation/start-trubudget.sh:137]: no, this is useful

File: scripts/operation/start-trubudget.sh (hunk 3 above)
Comment (daniel-arnauer) [reply scripts/operation/start-trubudget.sh:140]: done

File: docs/developer/developer-setup.md (hunk 7 above)
Comment (daniel-arnauer) [reply docs/developer/developer-setup.md:172]: there is only one step thanks to my all-in-one script

File: docs/developer/developer-setup.md (hunk 6 above)
Comment (daniel-arnauer) [reply docs/developer/developer-setup.md:161]: done

File: docs/developer/developer-setup.md (hunk 8 above)
Comment (daniel-arnauer) [reply docs/developer/developer-setup.md:200]: done

File: docs/developer/introduction.md (hunk 9 above)
Comment (daniel-arnauer) [reply docs/developer/introduction.md:118]: done

File: e2e-test/README.md (hunk 10 above)
Comment (daniel-arnauer) [reply e2e-test/README.md:5]: done - There are a lot of links, this should be resolved in a new issue

File: scripts/operation/start-trubudget.sh (hunk 4 above)
Comment (daniel-arnauer) [reply scripts/operation/start-trubudget.sh:203]: this todo will be done in the follow up issue #932

File: docs/developer/developer-setup.md (hunk 7 above)
Comment (mayrmartin) [reply docs/developer/developer-setup.md:174]: then remove leading 1

File: e2e-test/README.md (hunk 10 above)
Comment (mayrmartin) [reply e2e-test/README.md]: no. most of the direct links point to a readme in a sub project this is fine. this link points to the doc folder. pls use relative link instead.

**Comment by mayrmartin** [comment]
> To do:
> Edit dev.md, connect-docker-compose.md, create-new-docker-compose.md, update-trubudget.md.
> Add README.md for developer and operation bash script

pls add all relevant readme for doc

File: docs/developer/introduction.md (hunk 9 above)
Comment (mayrmartin) [reply docs/developer/introduction.md:118]: no. most of the direct links point to a readme in a sub project this is fine. this link points to the doc folder. pls use relative link instead.

File: .gitignore (hunk 12 above)
[the remark this answers is not in the document]
Comment (mayrmartin) [reply .gitignore]: add all env files to git ignore not only in scripts/development

File: docs/developer/developer-setup.md (hunk 7 above)
Comment (daniel-arnauer) [reply docs/developer/developer-setup.md:174]: no
