### PR TITLE
2087 Fix error handling between blockchain and email service

### LINKED ISSUE #2087: Wrong ExpiredTokenException error propagates throughout the application
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

Wrong error message in case of invalid algorithm makes debugging deployments harder, because it misleading.

### How to reproduce 🕹

1. <E.g. login as user XYZ>
2. <E.g. try to create new subproject>
3. <E.g. You will see error in console>
4. ...

### Screenshots 📷

Add screenshots or screen recording video if applicable.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.?.?  |
| API             | v2.?.?  |
| Blockchain      | v2.?.?  |
| Export-Service  | v2.?.?  |
| Email-Service   | v2.?.?  |
| Storage-Service | v2.?.?  |

### PR DESCRIPTION
**Pull request by SamuelPull**
### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [x] I fixed all necessary PR warnings
- [x] The commit history is clean
- [x] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [x] I did a self review before requesting a review from another team member

### How to test

1. <E.g. login as user XYZ>
2. <E.g. try to create new subproject>
3. <E.g. You should not see error in console>
4. ...

Closes #2087

### CODE REVIEW

File: blockchain/src/multichain-feed/email-notifications/sendNotifications.js [hunk 1]
```diff
@@ -154,8 +175,10 @@ const absolutePath = process.cwd() + "/" + path;
       if (error.name === "ExpiredTokenException") {
         token = createJWT(secret, "notification-watcher", algorithm);
         log.info("New JWT token created due to expiration.");
+      } else if (error.name === "InvalidAlgorithmException") {
+        log.error(error, `Notification e-mail request signed with invalid algorithm: ${algorithm}`);
       } else {
-        log.error("Error during notification processing:", error);
+        log.error(error, "Error during notification processing: ", error);
```
Comment (galethil) [inline blockchain/src/multichain-feed/email-notifications/sendNotifications.js:181]: @SamuelPull is there a reason for logging `error` twice?

Comment (SamuelPull) [reply blockchain/src/multichain-feed/email-notifications/sendNotifications.js:181]: no

**Review by galethil — APPROVED** [review]
