### PR TITLE
Fix simultaneous document upload

### LINKED ISSUE #972: Provisioning fails to upload documents simultaneously
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯
The provisioning fails to upload 2 documents in one API Call (workflowitem.update). This is because the API uploads the 2 documents to the storage-service simultaneously and the `verifyMinioBucket()` function leads to an error.

### How to reproduce 🕹
run `bash start-dev.sh --full --build` and see the logs
## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v1.25.0  |
| API             |v1.25.0  |
| Blockchain      | v1.25.0  |
| Export-Service  | v1.25.0  |
| Email-Service   | v1.25.0 |
| Storage-Service | v1.25.0  |

### PR DESCRIPTION
**Pull request by daniel-arnauer**
### Description
Follow up of https://github.com/openkfw/TruBudget/issues/946

### Solution
Instead of verifying that a valid minio bucket exists, the storage-service will throw an error with an explicit message to restart storage-service to initialize the minio container correctly (hence, a minio bucket will be created).

### How to test
To reproduce a setup with storage-service and minio, but without a minio bucket, see #946

Closes #972
Reverts commits from #953

### CODE REVIEW

File: api/src/service/domain/workflow/project_permission_revoke.ts [hunk 1]
```diff
@@ -61,9 +61,9 @@ export async function revokeProjectPermission(
   // Prevent revoking grant permission of last user
   const intents: Intent[] = ["project.intent.grantPermission"];
   if (
+    intent &&
     intents.includes(intent) &&
-    project.permissions[`${intent}`] !== undefined &&
-    project.permissions[`${intent}`].length === 1
+    project?.permissions[intent]?.length === 1
```
Comment (daniel-arnauer) [inline api/src/service/domain/workflow/project_permission_revoke.ts:66]: This fixes a new compiler error ["object could be undefined"]

File: api/src/service/Client_storage_service.ts [hunk 2]
```diff
@@ -48,6 +48,14 @@ export default class StorageServiceClient implements StorageServiceClientI {
     return this.axiosInstance.get("/readiness");
   }
 
+  public async verifyMinioBucket(): Promise<Result.Type<boolean>> {
+    const result = await this.axiosInstance.get("/verifyMinioBucket");
+    if (Result.isErr(result)) {
+      return new VError(result, "downloading object failed");
```
Comment (daniel-arnauer) [inline api/src/service/Client_storage_service.ts:54]: rewrite Verror message

File: storage-service/src/minio.ts [hunk 3]
```diff
@@ -199,16 +199,12 @@ const establishConnection = async () => {
...
   minioClient.listBuckets(function (err, buckets) {
     if (err) return console.log(err);
   });
 };
 
-if (config.storage.host) {
-  establishConnection();
-} else {
-  console.log("MINIO_ENDPOINT not set. Defaulting to chain storage.");
-}
```
Comment (daniel-arnauer) [inline storage-service/src/minio.ts]: This is dead code

File: storage-service/src/minio.ts [hunk 4]
```diff
@@ -57,7 +57,7 @@ const makeBucket = (bucket: string, cb: Function) => {
   });
 };
 
-const makeBucketAsPromised = (bucket: string) => {
```
Comment (georgimld) [inline storage-service/src/minio.ts:60]: This should be used on storage service start

Comment (georgimld) [reply storage-service/src/minio.ts:60]: Right now,  `establishConnection()` is not used anywhere

**Review by georgimld — CHANGES_REQUESTED** [review]

**Review by georgimld — APPROVED** [review]
