### PR TITLE
fix react highlighter warnings

### LINKED ISSUE #1115: frontend: Unexpecetd warnings on npm start SP 1
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

If I start the frontend I get following warning logs:

Compiled with warnings.
```
Failed to parse source map from '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/helpers.ts' file: Error: ENOENT: no such file or directory, open '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/helpers.ts'

Failed to parse source map from '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/highlight.tsx' file: Error: ENOENT: no such file or directory, open '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/highlight.tsx'

Failed to parse source map from '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/index.ts' file: Error: ENOENT: no such file or directory, open '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/index.ts'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

asset static/js/bundle.js 9.35 MiB [emitted] (name: main) 1 related asset
asset index.html 2.62 KiB [emitted]
asset asset-manifest.json 190 bytes [emitted]
cached modules 8.11 MiB (javascript) 29.3 KiB (runtime) [cached] 1933 modules

WARNING in ./node_modules/react-highlighter-ts/dist/lib/helpers.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/helpers.ts' file: Error: ENOENT: no such file or directory, open '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/helpers.ts'
 @ ./node_modules/react-highlighter-ts/dist/lib/highlight.js 25:16-36
 @ ./node_modules/react-highlighter-ts/dist/lib/index.js 8:18-40
 @ ./src/pages/SubProjects/SubProjectTable.js 24:0-49 187:41-50 212:41-50
 @ ./src/pages/SubProjects/SubProjects.js 13:0-48 25:66-81
 @ ./src/pages/SubProjects/SubProjectContainer.js 30:0-40 150:43-54
 @ ./src/pages/Main/Main.js 24:0-69 111:40-59
 @ ./src/index.js 26:0-37 112:29-33

WARNING in ./node_modules/react-highlighter-ts/dist/lib/highlight.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/highlight.tsx' file: Error: ENOENT: no such file or directory, open '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/highlight.tsx'
 @ ./node_modules/react-highlighter-ts/dist/lib/index.js 8:18-40
 @ ./src/pages/SubProjects/SubProjectTable.js 24:0-49 187:41-50 212:41-50
 @ ./src/pages/SubProjects/SubProjects.js 13:0-48 25:66-81
 @ ./src/pages/SubProjects/SubProjectContainer.js 30:0-40 150:43-54
 @ ./src/pages/Main/Main.js 24:0-69 111:40-59
 @ ./src/index.js 26:0-37 112:29-33

WARNING in ./node_modules/react-highlighter-ts/dist/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/index.ts' file: Error: ENOENT: no such file or directory, open '/home/stefan/github/TruBudget/frontend/node_modules/react-highlighter-ts/lib/index.ts'
 @ ./src/pages/SubProjects/SubProjectTable.js 24:0-49 187:41-50 212:41-50
 @ ./src/pages/SubProjects/SubProjects.js 13:0-48 25:66-81
 @ ./src/pages/SubProjects/SubProjectContainer.js 30:0-40 150:43-54
 @ ./src/pages/Main/Main.js 24:0-69 111:40-59
 @ ./src/index.js 26:0-37 112:29-33

3 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.71.0 compiled with 3 warnings in 2648 ms
```

### How to reproduce 🕹

Start frontend bare-metal with npm start

### PR DESCRIPTION
**Pull request by daniel-arnauer**
Replace Highlighter component with another one that is compatible with React 18
Fix other warnings

Closes #1115

### CODE REVIEW

File: frontend/src/pages/Overview/ProjectPermissionsContainer.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ class ProjectPermissionsContainer extends Component {
     const { permissions, myself, groups } = this.props;
     // get all permission that are assigned to the user
     const userPermissions = Object.keys(permissions).filter(intent => permissions[intent].includes(myself));
-    if (typeof groups === undefined || groups.length === 0 || groups == null) {
+    if (typeof groups === undefined || groups.length === 0 || groups === null) {
```
Comment (mayrmartin) [inline frontend/src/pages/Overview/ProjectPermissionsContainer.js:73]: good catch 😉

**Review by mayrmartin — COMMENTED** [review]
in the project list view, the filtering works, but the elements do not get highlighted. Pls also highlight them 

image

**Review by mayrmartin — APPROVED** [review]
