### PR TITLE
1918 storage-service: error logs

### LINKED ISSUE #1918: storage-service: missing error logs in storage-service server
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

### How to reproduce 🕹

1. <E.g. login as user XYZ>
2. <E.g. try to create new subproject>
3. <E.g. You will see error in console>
4. ...

### Screenshots 📷

Add screenshots or screen recording video if applicable.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v2.?.?  |
| API             | v2.?.?  |
| Blockchain      | v2.?.?  |
| Export-Service  | v2.?.?  |
| Email-Service   | v2.?.?  |
| Storage-Service | v2.?.?  |

### PR DESCRIPTION
**Pull request by SamuelPull**
### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [x] I fixed all necessary PR warnings
- [x] The commit history is clean
- [x] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [x] I did a self review before requesting a review from another team member

### How to test

1. <E.g. login as user XYZ>
2. <E.g. try to create new subproject>
3. <E.g. You should not see error in console>
4. ...

Closes #1918

### CODE REVIEW

File: storage-service/src/index.ts [hunk 1]
```diff
@@ -165,12 +165,7 @@ app.post(
...
       res.send({ docId, secret: result }).end();
     })().catch((err) => {
-      if (err.code === "NoSuchBucket") {
-        req.log.error(
-          { err },
-          "NoSuchBucket at /upload. Please restart storage-service to create a new bucket at minio/container in Azure blob storage",
-        );
-      }
+      req.log.error({ err }, "Error while uploading document");
       res.status(500).send(err).end();
```
Comment (galethil) [inline storage-service/src/index.ts:169]: @SamuelPull I would consider sending whole err object to the user as unsafe. But this is probably not part of this task.

Comment (SamuelPull) [reply storage-service/src/index.ts:169]: I agree 100%.  Client here is usually not a user, but an API server, and I didn't write the line you're referring to. I just added logging in a terminal of storage-service.  Moreover, at this point, I think it's more important for users to have some information they can report to us

File: storage-service/src/minio.ts [hunk 2]
```diff
@@ -12,6 +12,8 @@ import {
   sleep,
 } from "./storage";
 
+const region = process.env.MINIO_REGION || "us-east-1";
```
[the remark this answers is not in the document]
Comment (SamuelPull) [reply storage-service/src/minio.ts:15]: I'll update the docs. Region was hard-coded to us-east-1 before, no need to update deployment scripts.

**Review by MartinJurcoGlina — APPROVED** [review]
