### PR TITLE
api, storage-service, ui: delete uploaded document v2

### LINKED ISSUE #1488: Be able to delete an uploaded document of an open (not closed) workflow item
...in order to avoid validating a workflow item with a wrong document attached.

### PR DESCRIPTION
**Pull request by SamuelPull**
### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [x] I fixed all necessary PR warnings
- [x] The commit history is clean
- [x] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [x] I did a self review before requesting a review from another team member

### Description

Closes #1488

### CODE REVIEW

**Comment by pmolnar-dev** [comment]
From frontend and e2e tests it looks good. If someone could look at backend part it would be nice

File: api/src/service/domain/workflow/workflowitem_create.ts [hunk 1]
```diff
@@ -171,12 +171,7 @@ export async function createWorkflowitem(
   const documentUploadedEvents: BusinessEvent[] = [];
 
   if (reqData.documents?.length) {
-    const documentsCount = reqData.documents.filter((d) => d.base64).length;
```
Comment (galethil) [inline api/src/service/domain/workflow/workflowitem_create.ts:174]: @SamuelPull is there a reason you removed this lines? This was enabling a deployment without a storage service while still enable to use external links.

Comment (SamuelPull) [reply api/src/service/domain/workflow/workflowitem_create.ts:174]: no, git removed these when merging branches.
