### PR TITLE
Prevent provisioning from double provisioning

### LINKED ISSUE #561: prov: The provisioning exits when api is not reachable - SP 3
### Description
If the provisioning is started without having started the api the prov exits. The prov should retry instead.
While prov the prov should not generate any errors which is currently not the case.
Also sometime the prov is getting an error during prov and disconnects - it waits for 20 secs and go on without any problem again.

### TODO
Reproduce the error where prov exits without retrying.
Reproduce the error/s while provisioning.
Check solution ;)

### LINKED ISSUE #779: Provisioning should only run once - SP 4
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1. Provision the TruBudget chain
2. Provision it again

## Your Environment 🌎

| Tech           | Version |
| -------------- | ------- |
| Frontend       | v1.?.?  |
| API            | v1.?.?  |
| Blockchain     | v1.?.?  |
| Export-Service | v1.?.?  |
| Email-Service  | v1.?.?  |
| Chrome-Browser | ?       |
| etc.           |         |

### PR DESCRIPTION
**Pull request by daniel-arnauer**
Prevent provisioning from double provisioning

If the provisioning has already been successful, the provisioning aborts a second provisioning

If the provisioning has been falsy (no provisioning.ended flag set), the provisioning can be restarted normally

Closes #779 
Closes #561

### CODE REVIEW

File: api/src/provisioning_start.ts [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+interface RequestBodyV1 {
+  apiVersion: "1.0";
+  data: {};
+}
+
+const requestBodyV1Schema = Joi.object({
+  apiVersion: Joi.valid("1.0").required(),
+  data: Joi.object().empty().required(),
+});
+
```
Comment (daniel-arnauer) [inline api/src/provisioning_start.ts:20]: yes stefan, sending an empty object in a post call is best practice, if no paramater are needed

File: api/src/service/domain/workflow/provisioning_end.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+import * as Result from "../../../result";
+import { BusinessEvent } from "../business_event";
+import { NotAuthorized } from "../errors/not_authorized";
+import { ServiceUser } from "../organization/service_user";
+import * as ProvisioningEnded from "./provisioning_ended";
+
+export async function endProvisioning(
+  ctx: Ctx,
+  issuer: ServiceUser,
+): Promise<Result.Type<{ newEvents: BusinessEvent[] }>> {
```
Comment (Stezido) [inline api/src/service/domain/workflow/provisioning_end.ts:12]: why the type BusinessEvent [] is wrapped in an object? Can't it be returned directly?

File: api/src/service/domain/workflow/provisioning_start.ts [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+import * as Result from "../../../result";
+import { BusinessEvent } from "../business_event";
+import { NotAuthorized } from "../errors/not_authorized";
+import { ServiceUser } from "../organization/service_user";
+import * as ProvisioningStarted from "./provisioning_started";
+
+export async function startProvisioning(
+  ctx: Ctx,
+  issuer: ServiceUser,
+): Promise<Result.Type<{ newEvents: BusinessEvent[] }>> {
```
Comment (Stezido) [inline api/src/service/domain/workflow/provisioning_start.ts:12]: why the type BusinessEvent [] is wrapped in an object? Can't it be returned directly?

File: provisioning/package-lock.json [hunk 4]
```diff
@@ -3,2998 +3,6 @@
   "version": "1.20.0",
   "lockfileVersion": 2,
   "requires": true,
-  "packages": {
```
Comment (Stezido) [inline provisioning/package-lock.json:6]: build it with newer npm version

File: provisioning/package.json [hunk 5]
```diff
@@ -33,6 +33,7 @@
     "babel-eslint": "^10.1.0",
     "eslint": "^7.15.0",
     "eslint-config-airbnb-base": "^14.2.1",
+    "eslint-config-prettier": "^8.1.0",
```
Comment (Stezido) [inline provisioning/package.json:36]: what's our current lint/prettier situation? Do we follow a specific way to use prettier in combination with eslint in all projects?

File: api/src/system/getProvisioningState.ts [hunk 6]
```diff
@@ -0,0 +1,50 @@
+import { HttpResponse } from "../httpd/lib";
```
Comment (Stezido) [inline api/src/system/getProvisioningState.ts:1]: this is the wrong location for this kind of code.
This is the event sourcing of the system_information stream and should be located in the domain layer called system_information_eventsourcing. I would code it like the eventsourcing we already have.
a source function which applies all events where the apply method decides how to handle/apply the type of event.
Check out api/src/service/domain/workflow/global_permissions_eventsourcing.ts for an example

**Review by Stezido — CHANGES_REQUESTED** [review]
provisioning fails if I cancel it right before it will finish.
```
Project "Amazonas Fund" created.
Error: workflowitem 6634f85a0f5ac4b285a29567f0079de2 is not expected to already have documents attached. Note that the provisioning script shouldn't run more than once.
    at testWorkflowitemUpdate (/home/stefan/github/TruBudget/provisioning/src/index.js:349:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async runIntegrationTests (/home/stefan/github/TruBudget/provisioning/src/index.js:607:3)
    at async provisionBlockchain (/home/stefan/github/TruBudget/provisioning/src/index.js:652:7)
```
Request changes:
- Fix above error
- Why prov is logging "Now logged in as root" in the end? Missing logs or unnecessary login?
- if I start bc and api - then shut down bc after api is rdy - then start prov -> 
```
Server Error with status code undefined (connect ECONNREFUSED 127.0.0.1:8080), retry in 20 seconds
{ apiVersion: '1.0', error: { code: 500, message: '500 No Response' } }
```
- Remove error log when provisioning runs the first time.
```
[2021-04-14 10:46:10.775 +0000] ERROR (TruBudget on CPX-Z14FUDAJ0LV): Error during getProvisioningState method
    error: {
      "code": -708,
      "message": "Stream with this name not found: system_information"
    }
```


Checked/ Works as expected:
- provisioning events are saved onto system_information stream correctly.
- I also can't provision again if already provisioned

**Comment by daniel-arnauer** [comment]
Only the root user is allowed to write to the systeminfo stream, so before setting the provisioning_end flag, the user must be switched to root user.

File: provisioning/package.json (hunk 5 above)
Comment (daniel-arnauer) [reply provisioning/package.json:36]: Adjusted the eslint to rules of frontend since both are javascript projects. Also changed eslint config file from eslintrc.yml to .eslintrc for consistency.

File: provisioning/package-lock.json (hunk 4 above)
Comment (daniel-arnauer) [reply provisioning/package-lock.json:6]: done

File: api/src/service/domain/workflow/provisioning_start.ts (hunk 3 above)
Comment (daniel-arnauer) [reply api/src/service/domain/workflow/provisioning_start.ts:12]: done

File: api/src/service/domain/workflow/provisioning_end.ts (hunk 2 above)
Comment (daniel-arnauer) [reply api/src/service/domain/workflow/provisioning_end.ts:12]: done

File: api/src/service/Client.ts [hunk 7]
```diff
@@ -96,7 +96,7 @@ export class RpcMultichainClient implements MultichainClient {
     );
     return items.map((item) => ({
       key: item.keys[0],
-      value: hexToObject(item.data),
```
[the remark this answers is not in the document]
Comment (daniel-arnauer) [reply api/src/service/Client.ts:99]: this method is never in use except in getProvisioningState.ts. So I changed it that I can use it. 
Alternative approach: using v2_readStreamItems()

File: api/src/provisioning_end.ts [hunk 8]
```diff
@@ -0,0 +1,109 @@
...
+        if (Result.isErr(result)) {
+          throw new VError(result, "provisioning.end failed");
+        }
+        const code = 200;
+        const body = {
+          apiVersion: "1.0",
+          data: {},
+        };
+        reply.status(code).send(body);
+        reply.status(code).send(body);
```
[the remark this answers is not in the document]
Comment (daniel-arnauer) [reply api/src/provisioning_end.ts:102]: done

File: api/src/provisioning_start.ts [hunk 9]
```diff
@@ -0,0 +1,111 @@
...
+      .then((result) => {
+        if (Result.isErr(result)) {
+          throw new VError(result, "provisioning.start failed");
+        }
+        const code = 200;
+        const body = {
+          apiVersion: "1.0",
+          data: {},
+        };
+        reply.status(code).send(body);
```
[the remark this answers is not in the document]
Comment (daniel-arnauer) [reply api/src/provisioning_start.ts:103]: done

File: api/src/system/getProvisioningState.ts (hunk 6 above)
Comment (daniel-arnauer) [reply api/src/system/getProvisioningState.ts:1]: system considered calls are set in `router.ts`. This is the same patter that is used for` /liveness ` `/readiness`  `/version`

Comment (daniel-arnauer) [reply api/src/system/getProvisioningState.ts:1]: done

**Comment by daniel-arnauer** [comment]
The error
```
Project "Amazonas Fund" created.
Error: workflowitem 6634f85a0f5ac4b285a29567f0079de2 is not expected to already have documents attached. Note that the provisioning script shouldn't run more than once.
    at testWorkflowitemUpdate (/home/stefan/github/TruBudget/provisioning/src/index.js:349:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async runIntegrationTests (/home/stefan/github/TruBudget/provisioning/src/index.js:607:3)
    at async provisionBlockchain (/home/stefan/github/TruBudget/provisioning/src/index.js:652:7)
```

when aborting the provisioning between attaching documents and setting provision_ended flag is not wrong. In my opinion, this error should remain

File: provisioning/package.json (hunk 5 above)
Comment (daniel-arnauer) [reply provisioning/package.json:36]: Provisioning lint is already added in #794 , this commit can be removed

**Comment by daniel-arnauer** [comment]
Linting is already in master, so the commit for linting in provisioning can be removed

File: api/src/service/domain/workflow/system_information_eventsourcing.ts [hunk 10]
```diff
@@ -0,0 +1,51 @@
+import { Ctx } from "../../../lib/ctx";
```
Comment (Stezido) [inline api/src/service/domain/workflow/system_information_eventsourcing.ts:1]: why not using the structure of global_permissions_eventsourcing.ts - would be more especially regarding maintainability

File: api/src/service/provisioning_end.ts [hunk 11]
```diff
@@ -0,0 +1,28 @@
...
+  serviceUser: ServiceUser,
+): Promise<Result.Type<void>> {
+  const provisioningEndResult = await Cache.withCache(conn, ctx, async (cache) =>
+    ProvisioningEnd.endProvisioning(ctx, serviceUser),
+  );
+
+  if (Result.isErr(provisioningEndResult)) {
+    return new VError(provisioningEndResult, "end provisioning failed");
+  }
+
```
Comment (Stezido) [inline api/src/service/provisioning_end.ts:22]: make sure the event is valid by applying it again before actually storing it onto chain

File: api/src/service/provisioning_start.ts [hunk 12]
```diff
@@ -0,0 +1,28 @@
...
+  const provisioningStartResult = await Cache.withCache(conn, ctx, async (cache) =>
+    ProvisioningStart.startProvisioning(ctx, serviceUser),
+  );
+
+  if (Result.isErr(provisioningStartResult)) {
+    return new VError(provisioningStartResult, "start provisioning failed");
+  }
+
+  const provisioningStart = provisioningStartResult;
+
```
Comment (Stezido) [inline api/src/service/provisioning_start.ts:24]: make sure the event is valid by applying it again before actually storing it onto chain

File: api/src/service/provisioning_start.ts [hunk 13]
```diff
@@ -0,0 +1,28 @@
...
+import { ServiceUser } from "./domain/organization/service_user";
+import * as ProvisioningStart from "./domain/workflow/provisioning_start";
+import { store } from "./store";
+
+export async function startProvisioning(
+  conn: ConnToken,
+  ctx: Ctx,
+  serviceUser: ServiceUser,
+): Promise<Result.Type<void>> {
+  const provisioningStartResult = await Cache.withCache(conn, ctx, async (cache) =>
```
Comment (Stezido) [inline api/src/service/provisioning_start.ts:15]: what does provisioningStart mean? shouldn't it be a businessevent?

**Review by Stezido — CHANGES_REQUESTED** [review]
Regarding the provisioning issue:
If the error remains, the provisioning can never be finished and the blockchain must do a fresh install to be able to finish provisioning- this shouldn't be necessary just because of availability issues. solution is on e2e-test layer - the test is not written in the right way because the test seems to be dependent on another previous test

File: api/src/httpd/server.ts [hunk 14]
```diff
@@ -95,6 +95,7 @@ const registerSwagger = (
         { name: "notification" },
         { name: "project" },
         { name: "subproject" },
+        // add system_information ?
```
[the remark this answers is not in the document]
Comment (daniel-arnauer) [reply api/src/httpd/server.ts]: done

File: api/src/index.ts [hunk 15]
```diff
@@ -776,6 +782,22 @@ WorkflowitemsDocumentDownloadAPI.addHttpHandler(server, URL_PREFIX, {
...
+ProvisioningStartAPI.addHttpHandler(server, URL_PREFIX, {
+  startProvisioning: (ctx, user) => ProvisioningStartService.startProvisioning(db, ctx, user),
+});
+
+ProvisioningEndAPI.addHttpHandler(server, URL_PREFIX, {
+  endProvisioning: (ctx, user) => ProvisioningEndService.endProvisioning(db, ctx, user),
+});
+
+ProvisionedAPI.addHttpHandler(server, URL_PREFIX, {
+  getProvisioned: (ctx, user) => ProvisionedService.getProvisioned(db, ctx, user),
```
[the remark this answers is not in the document]
Comment (daniel-arnauer) [reply api/src/index.ts]: done

File: api/src/provisioned_get.ts [hunk 16]
```diff
@@ -0,0 +1,85 @@
+import { FastifyInstance } from "fastify";
```
[the remark this answers is not in the document]
Comment (daniel-arnauer) [reply api/src/provisioned_get.ts]: renamed to provisioning_get. I think a new folder is not necessary since there are also no other folders for projects, user, etc.

File: api/src/service/domain/workflow/system_information_eventsourcing.ts (hunk 10 above)
Comment (daniel-arnauer) [reply api/src/service/domain/workflow/system_information_eventsourcing.ts:1]: How? To get the provisioning status, we do not need to apply or validate events.

File: api/src/service/provisioning_end.ts (hunk 11 above)
Comment (daniel-arnauer) [reply api/src/service/provisioning_end.ts:22]: ?

Comment (daniel-arnauer) [reply api/src/service/provisioning_end.ts:22]: done - the events are applied in domain layer

File: api/src/service/provisioning_start.ts (hunk 12 above)
Comment (daniel-arnauer) [reply api/src/service/provisioning_start.ts:24]: done - the events are applied in domain layer

File: api/src/service/provisioning_start.ts (hunk 13 above)
Comment (daniel-arnauer) [reply api/src/service/provisioning_start.ts:15]: done - changed to provisioningStartEvent

File: api/src/service/domain/workflow/system_information_eventsourcing.ts (hunk 10 above)
Comment (daniel-arnauer) [reply api/src/service/domain/workflow/system_information_eventsourcing.ts:1]: Done

**Comment by daniel-arnauer** [comment]
The error
```
Project "Amazonas Fund" created.
Error: workflowitem 6634f85a0f5ac4b285a29567f0079de2 is not expected to already have documents attached. Note that the provisioning script shouldn't run more than once.
    at testWorkflowitemUpdate (/home/stefan/github/TruBudget/provisioning/src/index.js:349:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async runIntegrationTests (/home/stefan/github/TruBudget/provisioning/src/index.js:607:3)
    at async provisionBlockchain (/home/stefan/github/TruBudget/provisioning/src/index.js:652:7)
```

will not occur again. Instead, a warning is logged and new documents will not be attached to the current workflowitem. 

Hence, the provisioning can now run successfully again if the provision_end flag is not set.

**Review by Stezido — APPROVED** [review]
