### PR TITLE
Remove mui/styles

### LINKED ISSUE #1166: Remove peer deps in frontend
## Description 😯
`@mui/styles@5.8.0` and `connected-react-router` are not compatible with React 18:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @mui/styles@5.8.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!   peer react@">=16.8.0" from @emotion/react@11.9.0
npm ERR!   node_modules/@emotion/react
npm ERR!     @emotion/react@"^11.8.2" from the root project
npm ERR!     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.8.1
npm ERR!     node_modules/@emotion/styled
npm ERR!       @emotion/styled@"^11.8.1" from the root project
npm ERR!       3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!     3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!   22 more (@emotion/styled, @mui/base, @mui/icons-material, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from @mui/styles@5.8.0
npm ERR! node_modules/@mui/styles
npm ERR!   @mui/styles@"^5.5.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.0" from @mui/styles@5.8.0
npm ERR!   node_modules/@mui/styles
npm ERR!     @mui/styles@"^5.5.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### How to reproduce 🕹
Run `npm install` in frontend

### Solution
- [ ] wait for updates in connected-react-router
- [x] remove @mui/styles

### PR DESCRIPTION
**Pull request by daniel-arnauer**
### Description

Remove mui/styles since it is deprecated in MUI 5

Closes parts of #1166

### CODE REVIEW

File: frontend/src/languages/english.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ const en = {
       thousand: ",",
       precision: 2
     },
-    dateFormat: "dd/MM/yyyy",
+    dateFormat: "DD/MM/YYYY",
```
Comment (mayrmartin) [inline frontend/src/languages/english.js:9]: Date format in Englisch per default should be MM/DD/YYYY

Comment (daniel-arnauer) [reply frontend/src/languages/english.js:9]: nope, we use british english, so the format is correct:

https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_Kingdom
