### PR TITLE
ui: Group Permission

### LINKED ISSUE #440: ui: Granting permissions on a resource for groups doesn't work properly
### Description
Resource permissions granted for groups are ignored.
Tested examples:
- redaction of  workflowitems with view workflowitem permission
- Unable to view/grant/revoke permissions with view/grant/revoke permissions permission on workflowitem level

### PR DESCRIPTION
**Pull request by daniel-arnauer**
**Description Bug 1:**
As admin (mstein) at subproject-level "Set permissions for [subproject-name]" in "View permissions": when you set "View subproject details" (the loupe icon) for a user (eg.: jdoe)
then trubudget automatically adds the permission "View subproject overview". After this, when you disable "View subproject details" (the loupe icon), the overview line is still there. Gernerally, it should be disabled altough the user
still have the permission "View subproject details" (without seeing it because the element to view it has been disabled).
Happens on subproject-level and project-level.

**Description Bug 2:**
Granting group permission on project- and subproject-level made Issues. 
On Subproject-level, the fields "Grant subproject permissions" and "Revoke subproject permissions" have no affection when used with groups (it only works when you specify a person directly).
Same on project-level.
On workflow-item this bug does not occur.

**Description Bug 3:**
Confirmation Dialoge does not apply Group Permissions. Altough the right permissions are set in groups, the dialoge does not allow to continue granting new permission.

Closes #440

### CODE REVIEW

File: frontend/src/pages/SubProjects/SubprojectPermissionsContainer.js [hunk 1]
```diff
@@ -80,12 +83,31 @@ class SubProjectPermissionsContainer extends Component {
...
+      let groupIds = [];
+      filteredGroups.forEach((item, i) => (groupIds[i] = item.groupId));
+      // get all permissions from groups the user belongs to
+      const groupPerm = Object.keys(permissions).filter(intent =>
+        permissions[intent].some(member => groupIds.includes(member))
+      );
+      // remove duplicate permission (if User is in multiple groups with same permissions)
+      const combinedPerm = _uniq([...groupPerm, ...userPerm]);
+      return combinedPerm;
+    }
```
Comment (mathiashoeld) [inline frontend/src/pages/SubProjects/SubprojectPermissionsContainer.js]: see comments for other files

File: frontend/src/pages/Workflows/WorkflowItemPermissionsContainer.js [hunk 2]
```diff
@@ -90,6 +90,7 @@ class WorkflowItemPermissionsContainer extends Component {
   }
 
   render() {
+    console.log(this.props.workflowItems);
```
Comment (mathiashoeld) [inline frontend/src/pages/Workflows/WorkflowItemPermissionsContainer.js]: remove console.log

File: frontend/src/pages/Confirmation/ConfirmationDialog.js [hunk 3]
```diff
@@ -381,12 +387,27 @@ function isPermittedToGrant(identity, permissions, actions) {
...
-    if (!permissions[resource][`${resource}.intent.grantPermission`].includes(identity)) {
-      return false;
-    }
-    return true;
+  //check permission by username
+  const isUserPermitted = resourcesToCheck.every(resource => {
+    return permissions[resource][`${resource}.intent.grantPermission`].includes(username);
   });
+
+  if (typeof groups === undefined || groups.length === 0) {
```
[the remark this answers is not in the document]
Comment (daniel-arnauer) [reply frontend/src/pages/Confirmation/ConfirmationDialog.js]: added groups == null
