### PR TITLE
Fix bugs for backup and restore

### LINKED ISSUE #239: api: Backup and restore should be async
E.g. notification.list times out during creation of backup

### PR DESCRIPTION
**Pull request by georgimld**
Frontend Changes:
- at the frontend level, live updates for notification.list, project.viewDetails and subproject.viewDetails are paused while a backup is created or restored, because the api is not available during that time

Blockchain Changes:
- in the restore function, the rpc password will be checked so no backups with other rpc passwords will be allowed
- from now on, the name of the organisation will also be saved in the metadata.yml file when creating a new backup
- if a backup contains the organisation in the metadata file, it will also be checked when a user tries to restore a backup
- a new script was created as a workaround to issue #513, this issue should be fixed in TruBudget 2.0.0
- documentation on how to use the script was added

e2e-tests:
- test that a backup file can be downloaded
- test that an invalid backup cannot be restored 
- test that a valid backup with another organisation cannot be restored
- test that a valid backup can be restored

Closes #239

### CODE REVIEW

**Review by Stezido — CHANGES_REQUESTED** [review]
1. The backup e2e-test is failing maybe it's a timing issue (wait for responses before go on)
2. delete the failed test screenshots before pushing your changes (failed_restore_error.jpeg)
3. The names of the backup files are not quite clear - my suggestions are:
backup_valid ->valid_backup
backup_wrong_config -> backup_orga_test (If the orga is the "wrong config")
clean_backup -> provisioned_chain_backup
4. Create a Changelog entry because it's now possible to work around an " valid but invalid" backup file

File: e2e-test/cypress/integration/backup_spec.js [hunk 1]
```diff
@@ -0,0 +1,158 @@
+import "cypress-file-upload";
+let baseUrl, apiRoute;
+baseUrl = Cypress.env("API_BASE_URL") || `${Cypress.config("baseUrl")}/test`;
+apiRoute = baseUrl.toLowerCase().includes("test") ? "/test/api" : "/api";
+
+describe("Backup Feature", function() {
+  beforeEach(() => {
+    //the user must be logged out before each test
+    cy.url().then(url => {
+      cy.log(url);
```
Comment (Stezido) [inline e2e-test/cypress/integration/backup_spec.js:10]: remove it

**Review by Stezido — CHANGES_REQUESTED** [review]
Gj, after clean up commit messages the PR can be merged

**Review by Stezido — APPROVED** [review]
