### PR TITLE
ui: fix additional listPermission requirements

### LINKED ISSUE #738: Create workflowitem error because of missing permissions - 3SP
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

A user is sometimes not able to create a workflowitem because if the following error:
create workflowitem error
This happens when the user creating the workflowitem has the "create workflowitem" permission but does not have the "project view permissions" and "subproject view permissions" permission. The problem probably happens because the workflowitem assignment is not successful, which happens during the workflowitem creation.

## Steps to Reproduce 🕹
Steps:

1. User A creates a project and a subproject
2. User B is given the following permissions:

- view project in overview
- view project details
- view subproject in overview
- view subproject details
- create workflowitem

3. User B tries to create a workflowitem (assignee is not important, can be User B or A or some other user)
4. After user clicks on "Submit", the error is shown

## Solution
When the "create workflowitem" permission is assigned to a user, the project & subproject "view permisssions" and "grant permissions" permissions should be automatically assigned to the user (currently only the "view overview" and "view details" permissions are assigned)

### PR DESCRIPTION
**Pull request by daniel-arnauer**
In the confirmation dialog, the listpermission which may be required for other intents were not set correctly.

- [x] Check which intents require listPermissions
- [x] Add code to generate additional actions for listPermissions in confirmation dialog
- [x] ~~Add e2e-test~~ since refactoring is in progress, e2e tests will be added in PR #714 

Following intents are affected for listPermissions:
```
subproject.createWorkflowitem 
subproject.assign 
subproject.intent.grantPermission
subproject.intent.revokePermission

project.createSubproject
project.assign
project.intent.grantPermission
project.intent.revokePermission

workflowitem.assign
workflowitem.intent.grantPermission
workflowitem.intent.revokePermission
```

Closes #738

### CODE REVIEW

**Review by georgimld — APPROVED** [review]

File: e2e-test/cypress/integration/workflowitem_permissions_spec.js [hunk 1]
```diff
@@ -424,65 +443,25 @@ describe("Workflowitem Permissions", function() {
...
-
-    // Reset permissions
-    Cypress.Promise.all([
-      cy.revokeProjectPermission(projectId, "project.viewSummary", testUser.id),
-      cy.revokeProjectPermission(projectId, "project.viewDetails", testUser.id),
-      cy.revokeSubprojectPermission(projectId, subprojectId, "subproject.viewSummary", testUser.id),
-      cy.revokeSubprojectPermission(projectId, subprojectId, "subproject.viewDetails", testUser.id),
-      cy.revokeWorkflowitemPermission(projectId, subprojectId, workflowitemId, listPermIntent, testUser.id),
-      cy.revokeWorkflowitemPermission(projectId, subprojectId, workflowitemId, "workflowitem.update", testUser.id)
-    ]);
```
Comment (daniel-arnauer) [inline e2e-test/cypress/integration/workflowitem_permissions_spec.js:481]: removed because this test makes no sense
